// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GQ9_dnJrft7mCv3-ywAtjJOSuovE5Eg',
    appId: '1:761576156460:web:0d01331378c26055071089',
    messagingSenderId: '761576156460',
    projectId: 'fundamantalsofbiomedical',
    authDomain: 'fundamantalsofbiomedical.firebaseapp.com',
    storageBucket: 'fundamantalsofbiomedical.appspot.com',
    measurementId: 'G-REC0K30BR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFUTICh06CpTJI8NxnZIw9VieaCYZ2a94',
    appId: '1:761576156460:android:8442e7651839c83b071089',
    messagingSenderId: '761576156460',
    projectId: 'fundamantalsofbiomedical',
    storageBucket: 'fundamantalsofbiomedical.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLJTwJcWeKZFJP-vjeM4mt6aJCrG3ahHg',
    appId: '1:761576156460:ios:84d32584731e4318071089',
    messagingSenderId: '761576156460',
    projectId: 'fundamantalsofbiomedical',
    storageBucket: 'fundamantalsofbiomedical.appspot.com',
    iosBundleId: 'com.example.fundemetalsOfBiomedical',
  );
}
